/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("tasks").del();
  await knex("tasks").insert([
    {
      id: 1,
      name: "Find an island with football grounds",
      description: "The goal of this task is to find islands with football grounds that can host international matches",
      assigneeId: "4",
      reporterId: "1",
      createdDate: "2023-07-10",
      dueDate: "2024-07-10",
      taskStatus: "To-Do",
      projectId: "1",
    },
    {
      id: 2,
      name: "Improvise street skateboarding equipment along the streets in NY",
      description: "The aim of this task is to build skateboarding palques along the streets in NY",
      assigneeId: "4",
      reporterId: "1",
      createdDate: "2023-07-08",
      dueDate: "2023-10-10",
      taskStatus: "In-Progress",
      projectId: "3",
    },
    {
      id: 3,
      name: "Provide credentials for users of an online course",
      description: "Send out course info to users who are willing to start rapping",
      assigneeId: "1",
      reporterId: "1",
      createdDate: "2023-06-23",
      dueDate: "2023-12-23",
      taskStatus: "To-Do",
      projectId: "2",
    },
    {
      id: 4,
      name: "Inform teams about the island world cup",
      description: "Send out emails for teams making them aware about this world cup",
      assigneeId: "1",
      reporterId: "4",
      createdDate: "2023-05-18",
      dueDate: "2023-09-10",
      taskStatus: "To-Do",
      projectId: "1",
    },
    {
      id: 5,
      name: "Get permission from the muncipal council of the state of NY",
      description: "Visit the state of NY muncipal council and provide letters",
      assigneeId: "1",
      reporterId: "4",
      createdDate: "2023-05-18",
      dueDate: "2023-09-10",
      taskStatus: "To-Do",
      projectId: "3",
    },
    {
      id: 6,
      name: "Team registrations",
      description: "Send out forms for the teams to regsiter their teams",
      assigneeId: "1",
      reporterId: "4",
      createdDate: "2023-05-18",
      dueDate: "2023-09-10",
      taskStatus: "To-Do",
      projectId: "1",
    },
    {
      id: 7,
      name: "Gather team pics",
      description: "Send out a link for the teams to upload their team pics",
      assigneeId: "4",
      reporterId: "4",
      createdDate: "2023-05-18",
      dueDate: "2023-09-10",
      taskStatus: "To-Do",
      projectId: "1",
    },
    {
      id: 8,
      name: "Make the schedule",
      description: "Have a draw and create a schedule of the matches",
      assigneeId: "6",
      reporterId: "5",
      createdDate: "2023-05-18",
      dueDate: "2023-09-10",
      taskStatus: "To-Do",
      projectId: "1",
    },
    {
      id: 9,
      name: "Create a league on app",
      description: "Start a league on the app and share the invite link or the code with users to join",
      assigneeId: "6",
      reporterId: "1",
      createdDate: "2023-05-18",
      dueDate: "2023-07-10",
      taskStatus: "In-Progress",
      projectId: "4",
    },
    {
      id: 10,
      name: "Send out weekly flyers of Messi",
      description: "Have a scheduled time and day of the week to send out flyers of LM10",
      assigneeId: "6",
      reporterId: "2",
      createdDate: "2023-06-23",
      dueDate: "2023-08-10",
      taskStatus: "Done",
      projectId: "5",
    },
    {
      id: 11,
      name: "Validate the players",
      description: "Check for players emails and DOB and validate the players",
      assigneeId: "6",
      reporterId: "1",
      createdDate: "2023-07-11",
      dueDate: "2023-09-01",
      taskStatus: "To-Do",
      projectId: "4",
    },
    {
      id: 12,
      name: "Post flyers and raise awareness",
      description: "Raise awareness in the society about the academy by posting flyers about it",
      assigneeId: "6",
      reporterId: "4",
      createdDate: "2023-06-18",
      dueDate: "2023-09-28",
      taskStatus: "In-Progress",
      projectId: "6",
    },
    {
      id: 13,
      name: "Get feedback",
      description: "Gather user feedback after each session",
      assigneeId: "6",
      reporterId: "4",
      createdDate: "2023-06-18",
      dueDate: "2023-07-28",
      taskStatus: "To-Do",
      projectId: "6",
    },
  ]);
}
